services:
  - type: worker
    name: alb-forge
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8908394974:AAEoCVzAtD8xc_2N49rHP43HUIGrTEkYGX4"
      - key: ADMIN_IDS
        value: "6094686933"
      - key: TZ
        value: Asia/Ho_Chi_Minh
      - key: PYTHON_VERSION
        value: 3.11.9
